version: "3.9"

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./server:/server
    command: >
      bash -c
      "pip
      alembic upgrade head
      &&
      uvicorn main:app --reload --host 0.0.0.0 --port 8080
      "
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      REDIS_HOST: redis
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  usr-data:
